from flask_wtf import FlaskForm
from wtforms import StringField,PasswordField,SubmitField,BooleanField,RadioField,DateField,TextAreaField,SelectField,IntegerField,FloatField
from wtforms.validators import DataRequired,Length,EqualTo,ValidationError,Email,NumberRange,Optional
from flask_login import current_user
from hotel.models import *
from .authentication_forms import RegistrationForm,LoginForm
from .booking_forms import HotelSearchForm,GuestForm
from .customer_forms import AccountForm,ReviewForm,ContactForm,ComplaintForm
from .admin_forms import AddRoomForm,HotelForm,CreateAdminForm