"""Initial migration

Revision ID: 217e73141086
Revises: 
Create Date: 2026-06-29 15:57:19.668535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '217e73141086'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('amenities',
    sa.Column('amenity_id', sa.Integer(), nullable=False),
    sa.Column('amenity_name', sa.String(length=30), nullable=False),
    sa.Column('room_category', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('amenity_id')
    )
    with op.batch_alter_table('amenities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_amenities_amenity_name'), ['amenity_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_amenities_room_category'), ['room_category'], unique=False)

    op.create_table('contact_message',
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('contact_number', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('date_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('message_id')
    )
    with op.batch_alter_table('contact_message', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contact_message_contact_number'), ['contact_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_contact_message_date_time'), ['date_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_contact_message_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_contact_message_name'), ['name'], unique=False)

    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=70), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('role', sa.String(length=15), nullable=False),
    sa.Column('account_status', sa.String(length=20), nullable=False),
    sa.Column('created_date_time', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_account_status'), ['account_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_created_date_time'), ['created_date_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('audit_log',
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action_performed', sa.String(length=200), nullable=True),
    sa.Column('table_name', sa.String(length=100), nullable=True),
    sa.Column('record_id', sa.Integer(), nullable=True),
    sa.Column('action_datetime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_action_datetime'), ['action_datetime'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_action_performed'), ['action_performed'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_record_id'), ['record_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_table_name'), ['table_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_user_id'), ['user_id'], unique=False)

    op.create_table('customer__details',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('customer_name', sa.String(length=50), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('contact_number', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=70), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    with op.batch_alter_table('customer__details', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer__details_contact_number'), ['contact_number'], unique=False)

    op.create_table('hotel',
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.Column('hotel_name', sa.String(length=50), nullable=False),
    sa.Column('branch_name', sa.String(length=50), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('number_of_floors', sa.Integer(), nullable=False),
    sa.Column('contact_number', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.user_id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('hotel_id')
    )
    with op.batch_alter_table('hotel', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hotel_branch_name'), ['branch_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_hotel_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_hotel_hotel_name'), ['hotel_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_hotel_location'), ['location'], unique=False)
        batch_op.create_index(batch_op.f('ix_hotel_updated_by'), ['updated_by'], unique=False)

    op.create_table('room',
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('room_no', sa.Integer(), nullable=False),
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('beds', sa.String(length=20), nullable=False),
    sa.Column('current_price', sa.Float(), nullable=False),
    sa.Column('floor', sa.Integer(), nullable=False),
    sa.Column('room_status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.user_id'], ),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotel.hotel_id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('room_id'),
    sa.UniqueConstraint('hotel_id', 'room_no', name='uq_hotel_room')
    )
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_room_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_room_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_room_current_price'), ['current_price'], unique=False)
        batch_op.create_index(batch_op.f('ix_room_hotel_id'), ['hotel_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_room_room_no'), ['room_no'], unique=False)
        batch_op.create_index(batch_op.f('ix_room_room_status'), ['room_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_room_updated_by'), ['updated_by'], unique=False)

    op.create_table('booking',
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.Column('check_in_date', sa.Date(), nullable=False),
    sa.Column('check_out_date', sa.Date(), nullable=False),
    sa.Column('number_of_people', sa.Integer(), nullable=False),
    sa.Column('booking_status', sa.String(length=20), nullable=False),
    sa.Column('booking_date_time', sa.DateTime(), nullable=False),
    sa.Column('price_at_booking', sa.Float(), nullable=False),
    sa.Column('actual_check_in_datetime', sa.DateTime(), nullable=True),
    sa.Column('actual_check_out_datetime', sa.DateTime(), nullable=True),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotel.hotel_id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['room.room_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('booking_id')
    )
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_booking_booking_date_time'), ['booking_date_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_booking_status'), ['booking_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_check_in_date'), ['check_in_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_check_out_date'), ['check_out_date'], unique=False)

    op.create_table('complaint',
    sa.Column('complaint_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('booking_id', sa.Integer(), nullable=True),
    sa.Column('complaint_text', sa.Text(), nullable=True),
    sa.Column('complaint_datetime', sa.DateTime(), nullable=True),
    sa.Column('complaint_status', sa.String(length=30), nullable=True),
    sa.Column('resolution_details', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['booking.booking_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('complaint_id')
    )
    with op.batch_alter_table('complaint', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_complaint_booking_id'), ['booking_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_complaint_complaint_datetime'), ['complaint_datetime'], unique=False)
        batch_op.create_index(batch_op.f('ix_complaint_complaint_status'), ['complaint_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_complaint_user_id'), ['user_id'], unique=False)

    op.create_table('guest',
    sa.Column('guest_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('booking_id', sa.Integer(), nullable=True),
    sa.Column('guest_name', sa.String(length=30), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('contact_number', sa.String(length=20), nullable=False),
    sa.Column('number_of_people', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['booking.booking_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('guest_id')
    )
    with op.batch_alter_table('guest', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_guest_guest_name'), ['guest_name'], unique=False)

    op.create_table('payment',
    sa.Column('transaction_id', sa.String(length=100), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('transaction_date_time', sa.DateTime(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('payment_method', sa.String(length=30), nullable=False),
    sa.Column('payment_status', sa.String(length=20), nullable=False),
    sa.Column('receipt_number', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['booking.booking_id'], ),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_payment_status'), ['payment_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_receipt_number'), ['receipt_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_payment_transaction_date_time'), ['transaction_date_time'], unique=False)

    op.create_table('review',
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('booking_id', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('review_text', sa.Text(), nullable=True),
    sa.Column('review_datetime', sa.DateTime(), nullable=True),
    sa.Column('review_visibility', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['booking.booking_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('review_id'),
    sa.UniqueConstraint('booking_id')
    )
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_rating'), ['rating'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_review_datetime'), ['review_datetime'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_review_visibility'), ['review_visibility'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_user_id'), ['user_id'], unique=False)

    op.create_table('invoice',
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.String(length=100), nullable=False),
    sa.Column('tax_amount', sa.Float(), nullable=True),
    sa.Column('discount_amount', sa.Float(), nullable=True),
    sa.Column('final_amount', sa.Float(), nullable=True),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['payment.transaction_id'], ),
    sa.PrimaryKeyConstraint('invoice_id')
    )
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoice_invoice_date'), ['invoice_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoice_invoice_date'))

    op.drop_table('invoice')
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_user_id'))
        batch_op.drop_index(batch_op.f('ix_review_review_visibility'))
        batch_op.drop_index(batch_op.f('ix_review_review_datetime'))
        batch_op.drop_index(batch_op.f('ix_review_rating'))

    op.drop_table('review')
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_transaction_date_time'))
        batch_op.drop_index(batch_op.f('ix_payment_receipt_number'))
        batch_op.drop_index(batch_op.f('ix_payment_payment_status'))

    op.drop_table('payment')
    with op.batch_alter_table('guest', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_guest_guest_name'))

    op.drop_table('guest')
    with op.batch_alter_table('complaint', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_complaint_user_id'))
        batch_op.drop_index(batch_op.f('ix_complaint_complaint_status'))
        batch_op.drop_index(batch_op.f('ix_complaint_complaint_datetime'))
        batch_op.drop_index(batch_op.f('ix_complaint_booking_id'))

    op.drop_table('complaint')
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_booking_check_out_date'))
        batch_op.drop_index(batch_op.f('ix_booking_check_in_date'))
        batch_op.drop_index(batch_op.f('ix_booking_booking_status'))
        batch_op.drop_index(batch_op.f('ix_booking_booking_date_time'))

    op.drop_table('booking')
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_room_updated_by'))
        batch_op.drop_index(batch_op.f('ix_room_room_status'))
        batch_op.drop_index(batch_op.f('ix_room_room_no'))
        batch_op.drop_index(batch_op.f('ix_room_hotel_id'))
        batch_op.drop_index(batch_op.f('ix_room_current_price'))
        batch_op.drop_index(batch_op.f('ix_room_created_by'))
        batch_op.drop_index(batch_op.f('ix_room_category'))

    op.drop_table('room')
    with op.batch_alter_table('hotel', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hotel_updated_by'))
        batch_op.drop_index(batch_op.f('ix_hotel_location'))
        batch_op.drop_index(batch_op.f('ix_hotel_hotel_name'))
        batch_op.drop_index(batch_op.f('ix_hotel_created_by'))
        batch_op.drop_index(batch_op.f('ix_hotel_branch_name'))

    op.drop_table('hotel')
    with op.batch_alter_table('customer__details', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer__details_contact_number'))

    op.drop_table('customer__details')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_table_name'))
        batch_op.drop_index(batch_op.f('ix_audit_log_record_id'))
        batch_op.drop_index(batch_op.f('ix_audit_log_action_performed'))
        batch_op.drop_index(batch_op.f('ix_audit_log_action_datetime'))

    op.drop_table('audit_log')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_role'))
        batch_op.drop_index(batch_op.f('ix_user_email'))
        batch_op.drop_index(batch_op.f('ix_user_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_user_created_date_time'))
        batch_op.drop_index(batch_op.f('ix_user_account_status'))

    op.drop_table('user')
    with op.batch_alter_table('contact_message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contact_message_name'))
        batch_op.drop_index(batch_op.f('ix_contact_message_email'))
        batch_op.drop_index(batch_op.f('ix_contact_message_date_time'))
        batch_op.drop_index(batch_op.f('ix_contact_message_contact_number'))

    op.drop_table('contact_message')
    with op.batch_alter_table('amenities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_amenities_room_category'))
        batch_op.drop_index(batch_op.f('ix_amenities_amenity_name'))

    op.drop_table('amenities')
    # ### end Alembic commands ###
