"""Updated amenities model

Revision ID: d12587810c21
Revises: 217e73141086
Create Date: 2026-06-29 16:10:04.436164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd12587810c21'
down_revision = '217e73141086'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('amenities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hotel_id', sa.Integer(), nullable=False))
        batch_op.alter_column('amenity_name',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_amenities_hotel_id'), ['hotel_id'], unique=False)
        batch_op.create_foreign_key("fk_amenities_hotel_id", 'hotel', ['hotel_id'], ['hotel_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('amenities', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_amenities_hotel_id'))
        batch_op.alter_column('amenity_name',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
        batch_op.drop_column('hotel_id')

    # ### end Alembic commands ###
